Q1. Is there any difference in the data type of variables list_ and array_list? If there is, then write a code to print the data types of both variables.

In [1]:
import numpy as np
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)
# Q1
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)


Data type of list_: <class 'str'>
Data type of array_list: <U1


Q2. Write a code to print the data type of each and every element of both variables list_ and array_list.

In [2]:
# Q2
for element in list_:
    print("Data type of element in list_:", type(element))

for element in array_list:
    print("Data type of element in array_list:", type(element))


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.
Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [3]:
array_list = np.array(object=list_, dtype=int)
# Q3
print("Data type of list_:", type(list_[0]))
print("Data type of array_list:", array_list.dtype)

for element in list_:
    print("Data type of element in list_:", type(element))

for element in array_list:
    print("Data type of element in array_list:", type(element))
import numpy as np
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)


Data type of list_: <class 'str'>
Data type of array_list: int64
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size



In [4]:
# Q4
print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


Q5. Write a code to create a NumPy array of a 3*3 matrix containing zeros only, using a NumPy array creation function.

In [5]:
# Q5
zero_array = np.zeros((3, 3))
print("Zero array:")
print(zero_array)


Zero array:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5,5) using NumPy functions?

In [6]:
# Q6
identity_matrix = np.eye(5)
print("Identity matrix:")
print(identity_matrix)


Identity matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
